version: "3"
services:
  amplify:
    build: ./
    ports:
      - "3000:3000"
      - "20002:20002"
    volumes:
      - ./:/var/www/amplify
      - ./:/root/.aws/
    command: sh -c "cd next-app && npm install && npm run dev"
    tty: true
